spring:
  application:
    name: message-bridge-service
  
  cloud:
    function:
      definition: processMessage
    stream:
      binders:
        rabbit-source:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${RABBITMQ_SOURCE_HOST:localhost}:${RABBITMQ_SOURCE_PORT:5672}
                username: ${RABBITMQ_SOURCE_USER:admin}
                password: ${RABBITMQ_SOURCE_PASSWORD:admin123}
                virtual-host: ${RABBITMQ_SOURCE_VHOST:/}
        rabbit-destination:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${RABBITMQ_DESTINATION_HOST:localhost}:${RABBITMQ_DESTINATION_PORT:5673}
                username: ${RABBITMQ_DESTINATION_USER:admin}
                password: ${RABBITMQ_DESTINATION_PASSWORD:admin123}
                virtual-host: ${RABBITMQ_DESTINATION_VHOST:/}
      
      bindings:
        processMessage-in-0:
          destination: source.queue
          group: message-bridge-group
          binder: rabbit-source
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        processMessage-out-0:
          destination: destination.queue
          binder: rabbit-destination
          producer:
            required-groups: destination-group
      
      rabbit:
        bindings:
          processMessage-in-0:
            consumer:
              acknowledge-mode: auto
              durable: true
              prefetch: 10
          processMessage-out-0:
            producer:
              routing-key-expression: '''destination'''
              exchange-type: direct
              durable: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.messagebridge: DEBUG
    org.springframework.cloud.stream: INFO
    org.springframework.amqp: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"