spring:
  application:
    name: message-bridge-service
  
  cloud:
    function:
      definition: processMessage;processRabbitToKafka;processKafkaToRabbit
    stream:
      binders:
        rabbit-source:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${RABBITMQ_SOURCE_HOST:localhost}:${RABBITMQ_SOURCE_PORT:5672}
                username: ${RABBITMQ_SOURCE_USER:guest}
                password: ${RABBITMQ_SOURCE_PASSWORD:guest}
                virtual-host: ${RABBITMQ_SOURCE_VHOST:/}
        rabbit-destination:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${RABBITMQ_DESTINATION_HOST:localhost}:${RABBITMQ_DESTINATION_PORT:5673}
                username: ${RABBITMQ_DESTINATION_USER:guest}
                password: ${RABBITMQ_DESTINATION_PASSWORD:guest}
                virtual-host: ${RABBITMQ_DESTINATION_VHOST:/}
        kafka-source:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: ${KAFKA_SOURCE_BROKERS:localhost:9092}
                consumer:
                  group-id: message-bridge-kafka-source
                  auto-offset-reset: earliest
        kafka-destination:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: ${KAFKA_DESTINATION_BROKERS:localhost:9093}
                producer:
                  key-serializer: org.apache.kafka.common.serialization.StringSerializer
                  value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
      bindings:
        # Original RabbitMQ to RabbitMQ bridge
        processMessage-in-0:
          destination: source.queue
          group: message-bridge-group
          binder: rabbit-source
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        processMessage-out-0:
          destination: destination.queue
          binder: rabbit-destination
        
        # RabbitMQ to Kafka bridge
        processRabbitToKafka-in-0:
          destination: rabbit.to.kafka.queue
          group: rabbit-to-kafka-group
          binder: rabbit-source
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        processRabbitToKafka-out-0:
          destination: kafka-destination-topic
          binder: kafka-destination
        
        # Kafka to RabbitMQ bridge
        processKafkaToRabbit-in-0:
          destination: kafka-source-topic
          group: kafka-to-rabbit-group
          binder: kafka-source
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
        processKafkaToRabbit-out-0:
          destination: kafka.to.rabbit.queue
          binder: rabbit-destination
      
      rabbit:
        bindings:
          processMessage-in-0:
            consumer:
              acknowledge-mode: auto
              durable: true
              prefetch: 10
          processMessage-out-0:
            producer:
              routing-key-expression: '''destination'''
              exchange-type: direct
              durable: true
          processRabbitToKafka-in-0:
            consumer:
              acknowledge-mode: auto
              durable: true
              prefetch: 10
          processKafkaToRabbit-out-0:
            producer:
              routing-key-expression: '''kafka-to-rabbit'''
              exchange-type: direct
              durable: true
      
      kafka:
        bindings:
          processRabbitToKafka-out-0:
            producer:
              key-serializer: org.apache.kafka.common.serialization.StringSerializer
              value-serializer: org.apache.kafka.common.serialization.StringSerializer
          processKafkaToRabbit-in-0:
            consumer:
              auto-offset-reset: earliest

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.messagebridge: DEBUG
    org.springframework.cloud.stream: INFO
    org.springframework.amqp: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"